### ISSUE TITLE
Add CSS to 

### ISSUE THREAD

**Issue by jamespostsil** [sillsdev/docu-notion#105]
Could we please add these to custom.css? They will both help with usability of the Bloom Docs. The links show some examples of the before/after.

**Docu-Notion defaults sub-ordered lists to `i, ii, iii`. It's easier/better to use `a, b, c`. SnagIt supports using `a, b, c`.**

See [Change sub-ordered lists to a, b, c](https://www.notion.so/hattonjohn/Current-Docusaurus-Issues-ee7d95d8866f4599a7c98785dfe1cd64?pvs=4#4b197f4242bf4c16bc6af3a6da531676).

CSS code:

```
/* Make sub-ordered lists use lowercase a, b, c instead of i, ii, iii. */
ol ol {
  list-style-type: lower-alpha;
}
```

**It's easier to see bold titles for toggles.**

See [Add bold to toggle titles](https://www.notion.so/hattonjohn/Current-Docusaurus-Issues-ee7d95d8866f4599a7c98785dfe1cd64?pvs=4#e1d73358db3a4dbb90f64b4b40489eb8).

CSS code:

```
/* Add bold text to the "title" of toggles" */
details summary {
  font-weight: var(--ifm-font-weight-bold);
}
```

**Comment by andrew-polk** [comment]
This is actually a bloom-docs issue.
I've moved it to https://github.com/BloomBooks/bloom-docs/issues/9
