### ISSUE TITLE
Text in lists can break mdx parser, should be escaped for html safety

### ISSUE THREAD

**Issue by hatton** [sillsdev/docu-notion#21]
![image](https://user-images.githubusercontent.com/8448/204601943-338c99e1-703e-4188-9137-ed29f4d3b1d1.png)

docu-notion makes this into

```
 <li parentName="ol"><strong parentName="li">{`Dropbox`}</strong>{` will ask whether you want to “Remove `}<book title>{` from your Dropbox account and all devices?” Click “Move out of Dropbox”. If you do not want to see such notices in the future, you can tick the box “Don’t ask me this again”.`}</li>
```

Instead, the text should be encoded so that it doesn't mess up the html parser.
Q: what if there is content in there that we *do* want to be parsed?

**Comment by andrew-polk** [comment]
It isn't easy to know when we want to to do this or not.
For now, I've made it simply change `<` to `&lt;` and `<` to `&gt;` unless it is a code block.
But we could do fancier things in the future like not escape it if it has a matching closing tag or is a self-closing tag.
We could also not escape if the text is wrapped in backticks (`).
