### ISSUE TITLE
[Feature] PDF downloads in French and Spanish

### ISSUE THREAD

**Issue by fraserbennett** [sillsdev/docu-notion#29]
**Problem**
[PDF Downloads](https://docs.bloomlibrary.org/downloads) currently has only English available, even if the top-nav language is set to [français](https://docs.bloomlibrary.org/fr/downloads/) or [español](https://docs.bloomlibrary.org/es/downloads/)

URLs: 
* https://docs.bloomlibrary.org/es/downloads/
* https://docs.bloomlibrary.org/fr/downloads/

**Expected behavior**
- If a localized page exists, show that page. 
- If no localized page exists, show the English-language page with a banner (in the requested language) saying that there is no localized page. 
![es-downloads](https://user-images.githubusercontent.com/12233151/207385374-f9b29c8e-afb1-4115-9ca5-64a3a880747d.png)

**Comment by hatton** [comment]
@fraserbennett this is a library used by various sites. Your issue would go on the repo for that site, which is here: https://github.com/BloomBooks/bloom-docs/issues

**Comment by fraserbennett** [comment]
@hatton OK, thanks for directing the bull to the right china shop. ;^)
