### ISSUE TITLE
Support Notion Synced Blocks

### ISSUE THREAD

**Issue by dionjwa** [sillsdev/docu-notion#34]
**Describe the bug**
Synced blocks that are linked to the original are not rendered. The original synced block is rendered.

** Reproduction Steps **

https://www.notion.so/metapages/Facts-mermaid-63f6f281a33649cc9dfabb86d26ad829

The first mermaid diagram is not a synced block, and renders fine.

The second block is a synced block, and renders fine in this page, but another page has a linked to that synced mermaid block:

https://www.notion.so/metapages/Introduction-to-docu-notion-779f83504bd94642a9b87b2afc810a97

**Expected behavior**
Linked synced blocks show the exact contents of the original synced block

**Screenshots**

**Additional context**

**Comment by dionjwa** [comment]
This is solved by upgrading the `notion-to-md` package where this issue was fixed, however, upgrading fully breaks this module (returning `[object Object]` in place of rendered markdown)

**Comment by andrew-polk** [comment]
Please try the alpha which has upgraded notion-to-md to the latest.

**Comment by dionjwa** [comment]
Yeah, it works with the latest. You can close this.
