### ISSUE TITLE
Numbered lists don't continue

### ISSUE THREAD

**Issue by JenniBeadle** [sillsdev/docu-notion#35]
**Describe the bug**
Numbered lists restart at 1 after subheading even when given a specific starting number after the heading.
Having just looked at the Notion markdown, I think it may be a Notion bug not a docu-notion bug.

**Reproduction Steps**
I have 25 chapters in my Paratext Manual. In the overview I break them up into sections but need the sequential numbering to continue so it shows correct chapter number.
Add a numbered list with headings.
Edit each list item after the heading with the number to continue.
Notion displays correctly.
But the resulting page restarts the numbering.

URL of a source Notion page that, when docu-notion accesses or converts it, shows the problem:
Notion: https://jennibeadle.notion.site/Overview-of-Training-Manual-3ce84f9ca3264aed8532489c0574f95c
Resulting page: https://sillsdev.github.io/paratext-manual/Overview/

**Expected behavior**
Numbering should continue (as per my other Docusaurus site.
https://manual.paratext.org/Training-Manual/Overview

**Notion markdown**
The notion markdown still has 1. 

    ### Stage 1 Drafting

    1. 2. **[OD** – Organising your desktop](https://sillsdev.github.io/paratext-manual/2.OD)
    2. **[PP1** – Project plan and progress](https://sillsdev.github.io/paratext-manual/3.PP1)
I added the 2. to specify to continue from 2 but it still has the 1.
I corrected the markdown and pasted it again but it added the 1. again.  

**Screenshots**
_In Notion: showing the continuer set_
<img width="234" alt="image" src="https://user-images.githubusercontent.com/108683165/210311780-da6ca210-bee4-4921-941f-c43b29d9814f.png">

_Result of Docu-notion (showing restart as 1):_ 
<img width="170" alt="image" src="https://user-images.githubusercontent.com/108683165/210311448-d34b8deb-51db-42a8-b256-b8edc81867be.png">  

_Site using Markdown (sequential):_ 
<img width="214" alt="image" src="https://user-images.githubusercontent.com/108683165/210311513-6895c3bc-b6f2-479a-8843-6bcb24e85c82.png">

 
**Additional context**
I searched for possible solutions.
https://stackoverflow.com/questions/18088955/markdown-continue-numbered-list/22138846#22138846
suggested putting a blank link before the element (in their case a code block) but had no effect.

**Comment by hatton** [comment]
Yeah, this was reported to Notion [here](https://github.com/makenotion/notion-sdk-js/issues/292#issuecomment-1279768477), and I also tried with Notion's email support back i October, but didn't get anywhere.

**Comment by hatton** [comment]
I did have success indenting the text.

![image](https://user-images.githubusercontent.com/8448/210381486-55cec47c-0d2e-466b-abf4-261465857192.png)

Yielded
![image](https://user-images.githubusercontent.com/8448/210381547-24c5e066-7913-40d9-992d-267b01b0dec3.png)

Which was rendered as

![image](https://user-images.githubusercontent.com/8448/210381414-47e570a6-1f02-4683-befa-5517075f8609.png)

**Comment by JenniBeadle** [comment]
Not sure about indenting headings. But I guess I could turn the headings into text and bold them.

**Comment by JenniBeadle** [comment]
Doesn't work with non-indented bold text blocks. :(

**Comment by hatton** [comment]
Notion wrote back saying that they are not going to fix this in the API. So without that, we can't support this, sorry.

**Comment by hatton** [comment]
Anyone having this problem, please make yourself heard by writing to Notion. They rejected my request for a fix, but said that they might act on it if more people asked. So please ask!  See: https://github.com/makenotion/notion-sdk-js/issues/292
