### ISSUE TITLE
Search only works on front page

### ISSUE THREAD

**Issue by JenniBeadle** [sillsdev/docu-notion#37]
**Describe the bug**
The search add-in only finds results when used from the front page (intro page with slug /) and only hits on that page.

** Reproduction Steps **
- Go to the intro page
- Click in the search box
- Type a word
   - only finds words on that page.

- Go to another page
- Click in the search box
- Start to type a word
- No results error
- 
URL of a source Notion page that, when docu-notion accesses or converts it, shows the problem:

URL of a docusuarus site showing the resulting page
https://sillsdev.github.io/paratext-manual/00-list-of-features/

**Expected behavior**
Expect to get results from all the pages.

**Screenshots**
Screenshot shows no result even when several results clearly seen on page
<img width="437" alt="image" src="https://user-images.githubusercontent.com/108683165/210387218-efbb39c4-d434-4e77-8121-7f8f56586b7d.png">

**Additional context**
I checked the docusaurus.config.js and removed the comment on languages for the plug-in. It looks identical to my other working site.

**Comment by hatton** [comment]
Docu-notion isn't connected to the docusaurus search in any way I can think of. Search is definitely working in https://docs.bloomlibrary.org/, and hopefully [the config for that](https://github.com/bloomBooks/bloom-docs) will be of help to you.

**Comment by JenniBeadle** [comment]
Thanks for confirming that search works on your site using your system. 
I already confirmed it works on my manual.paratext.org with Docusaurus as well. 
Since **you did the config** for paratext-manual it was the same 😄.

BTW The link to your config didn't help. It showed how to add a locale, not configuring the search. But I could see that further down. 

When I did set up the search on my manual.paratext.org site there were two steps - edit the config and install the plug-in/theme. If it wasn't installed then I would get an roi error. So it has to be installed. we have confirmed the config is right. So I am wondering if we need to **re-install the plug-in**. 

I don't understand how to run these commands on your system. Do I need to get you to do it, or is there anything I can do?

**Comment by andrew-polk** [comment]
I'm not sure what you mean by reinstalling the plugin.

I suspect(ed) it had to do with this setting: `baseUrl: "/paratext-manual/"` (bloom-docs has `baseUrl: "/"`).
But I played around with it a little yesterday and couldn't figure it out.

**Comment by JenniBeadle** [comment]
Sounds like you are having as much trouble understanding running Docusaurus from the command line as I am understanding your system. 

### My old paratext-notion works
I have an old repository on GitHub called paratext-notion. This was my first attempt at using Notion for Docusaurus. At the time docu-notion wasn't as advanced as it is now and wasn't downloading  properly to my computer. So John Hatton set up this repository and its configuration as he couldn't work with my repository in my GitHub. 

I checked that GitHub repository and it now works and most importantly the search works! 
https://jennibeadle.github.io/paratext-notion/ 

The config has:
url: 'https://JenniBeadle.github.io',
**baseUrl: '/paratext-notion/',**

So I think we can rule out the base-url as the cause of the problem.
BTW when I deploy the live Paratext manual to a custom domain _manual.paratext.org_ I had to change the baseurl to "/" so I think it has more to do with where it is deployed rather than affecting the search.

### Installing the search from the command line
On command line Docusaurus, to get search working you need to first install easyops... from the command line. Then you add it into your docusaurus.config.js. I have checked the config so my next thought would be to reinstall the "plug-in/theme".
> Notice: We present this as a theme instead of plugin now.

## Command line installation
The instruction on  https://github.com/easyops-cn/docusaurus-search-local
     **Installation**
     npm install --save @easyops-cn/docusaurus-search-local
      or
     yarn add @easyops-cn/docusaurus-search-local
     **Usage**
     Add @easyops-cn/docusaurus-search-local into your docusaurus **themes**.

I was able to do the npm install on my paratext-notion repository as I had a downloaded copy on my computer but have no idea how to do things directly on the paratext-manual github repository.

But you must have a way of running the Docusaurus commands from your end. Don't you?

**Comment by hatton** [comment]
I'm going to close this as it is apparently not related to this repository (docu-notion). Feel free to reach out to us via email for Docusaurus help.

**Comment by JenniBeadle** [comment]
I respectfully disagree. But which email can I reach out for help?

**Comment by andrew-polk** [comment]
I'll email you to begin a dialog on this.
