### ISSUE TITLE
Make GitHub Actions see Errors (and Warnings)

### ISSUE THREAD

**Issue by JenniBeadle** [sillsdev/docu-notion#42]
**Describe the bug**
Any warnings in "Build Github Pages" of the Release are not shown to the user.  
It was only in trouble-shooting another site that I discovered them in the release.

**Reproduction Steps**
1. Go to GitHub pages for your site
2. Click on Actions tab
3. Click on a previous **Release**
  <img width="236" alt="image" src="https://user-images.githubusercontent.com/108683165/216280513-976d6e72-a1e8-4aed-acd5-d6e85e6c37f9.png">
4. Click on the **Release** on the next page
 <img width="267" alt="image" src="https://user-images.githubusercontent.com/108683165/216280711-4a1c7caf-92a9-425b-a397-fcb88f355592.png">
5. Expand "Build Github Pages"  

6. Look for Warnings. (see screenshot below)

**URL of a source Notion page that, when docu-notion accesses or converts it, shows the problem:**
https://jennibeadle.notion.site/Stage-3-Preparing-for-the-Consultant-check-b2e2a08bd0f44a7da06333d46250331c 

**URL of GitHub showing the warnings**
https://github.com/sillsdev/paratext-manual/actions/runs/4060888616/jobs/6990404972

**URL of Docusaurus page**
https://sillsdev.github.io/paratext-manual/Stage-3

**Expected behavior**
If there are warnings, the user should be informed.
The Release ran without any errors.  So I was most surprised to stumble across the warnings.

**Screenshots**  
Screenshot show warnings  
I<img width="624" alt="image" src="https://user-images.githubusercontent.com/108683165/216276566-a8b14ec2-755d-4541-bd66-f1d674b10bef.png">

**Comment by hatton** [comment]
OK, some progress on this.  With v10.0, we now get

![image](https://user-images.githubusercontent.com/8448/217056563-22ead0f6-1b78-4805-8407-bd981e9ddfee.png)

and

![image](https://user-images.githubusercontent.com/8448/217056385-41782e6c-6b55-44f7-a723-bbc85d3b0838.png)

**Comment by hatton** [comment]
We also now get "grouped" sections in the log:

![image](https://user-images.githubusercontent.com/8448/217110412-6c3ffd08-bddb-4763-804a-d3dbdb9012e9.png)
