### ISSUE TITLE
Any update on crowdin support?

### ISSUE THREAD

**Issue by JenniBeadle** [sillsdev/docu-notion#45]
I am testing crowdin support. Docusaurus.io gives the CLI commands which work from my computer. 

Are there any plans to make Actions for crowdin to work on github repositories from Notion?

**Comment by andrew-polk** [comment]
This would not become part of docu-notion.
Someday it might get documented in https://github.com/sillsdev/docu-notion-sample-site.
For now, you could look at 
https://github.com/BloomBooks/bloom-docs/blob/master/.github/workflows/release.yml
and
https://github.com/BloomBooks/bloom-docs/blob/master/package.json
to see how we are doing it for docs.bloomlibrary.org.

**Comment by JenniBeadle** [comment]
Thanks. It is obviously too long for you  to help me understant it and apply it. But two things stand out. 
- You are using **made-pdf** - has that replaced **docu-pdf**?
- You are using **AWS** instead of an Integration which I am trying. Are **Integrations** OK?

**Comment by hatton** [comment]
Bloom-Docs does use `docu-pdf`. `make-pdf` is just the name of a script in our `package.json`. I don't know what an "Integration" is, but yes, you can store your site wherever you want. For example, the [docu-notion sample site](https://sillsdev.github.io/docu-notion-sample-site/) uses github pages.
