### ISSUE TITLE
Screenshot localisation

### ISSUE THREAD

**Issue by JenniBeadle** [sillsdev/docu-notion#46]
I am about to recreate our paratext-manual site. The information on the README file about localisation is out of date. Do you have any updates to your process/suggestions for localising screenshots?

Thanks

**Comment by JenniBeadle** [comment]
Well, maybe somewhat inaccurate is more precise than out of date. From your question I gather that means that you still follow this process? Let me add some comments below.

> Screenshot Localization
> The only way we know of to provide localization of image in the current Docusaurus (2.0) is to place the images in the same directory as the markdown, and use relative paths for images. 

**JB**: I usually place the image in a media subfolder not the same directory. But them maybe that's what you actually meant.

> Most projects probably won't localize every image, so we also need a way to "fall back" to the original screenshot when the localized one is missing. docu-notion facilitates this. If no localized version of an image is available, docu-notion places a copy of the original image into the correct location.


**JB** All my projects localise **EVERY** image.

> So how do you provide these localized screenshot files? Crowdin can handle localizing assets, and in the future we may support that. For now, we currently support a different approach. If you place for example fr https:\\imgur.com\1234.png in the caption of a screenshot in Notion, docu-notion will fetch that image and save it in the right place to be found when in French mode. Getting URLs to screenshots is easy with screenshot utilities such as [Greenshot](https://getgreenshot.org/) that support uploading to imgur. Note that docu-notion stores a copy of all images in your source tree, so you wouldn't lose the images if imgur were to go away.

**JB**: Sounds like you still don't use Crowdin for screenshots. **Can I confirm that with your system you still need to manually capture each screenshot in the localised language?** But then you send it to imgur?
But I presume you use Crowdin for text?  


> NOTE: that as far as I can tell, when you run docusaurus start docusaurus 2.0 offers the language picker but it doesn't actually work. So to test out the localized version, do docusaurus build followed by docusaurus serve.

**JB**: when you use docusaurus start on the command line it uses the default locale. If you want a different locale you need to specify it 

e.g.  npm run start -- --locale fr

> NOTE: if you just localize an image, it will not get picked up. You also must localize the page that uses the image. Otherwise, Docusaurus will use the English document and when that asks for ./the-image-path, it will find the image there in the English section, not your other language section.

**JB**: True.

**Comment by hatton** [comment]
> Sounds like you still don't use Crowdin for screenshots. Can I confirm that with your system you still need to manually capture each screenshot in the localised language? But then you send it to imgur?
But I presume you use Crowdin for text?

Yes, in our own use of `docu-notion`, we store localized images on imgur.  But `docu-notion` doesn't care where you store them, so long as you give it a url.

Yes, in our own use of `docu-notion`, we use Crowdin. ([our github actions file](https://github.com/BloomBooks/bloom-docs/blob/master/.github/workflows/release.yml))

**Comment by andrew-polk** [comment]
@JenniBeadle 
I believe this has been resolved. Ok if we close this issue?

**Comment by JenniBeadle** [comment]
Yes, go ahead and close this issue. It wasn’t really an issue, just an attempt to share information.
