### ISSUE TITLE
Notion page not found

### ISSUE THREAD

**Issue by purplecarrot625** [sillsdev/docu-notion#57]
**Describe the bug**
`Notion page not found "${uuidToId(pageId)}") ^ Error: Notion page not found "454a4e53ed0a46f6bd431b07328e8941".
I always met this error, and was stuck at stage 2.

![image](https://github.com/sillsdev/docu-notion/assets/97133994/2e3395b9-a995-43b5-8b92-6bb14ec77df6)

Only several pages that I can load in my directory tree. ;(
Any help is appreciated!!

**Comment by andrew-polk** [comment]
We would need more information to help you, but I'll take a guess at what may be happening based on the log you've shown:
It appears maybe you duplicated and modified our sample site on Notion but left a link to 454a4e53ed0a46f6bd431b07328e8941 which is on our sample site but not yours.
Or perhaps 454a4e53ed0a46f6bd431b07328e8941 is a page on your notion site but it hasn't been published?

**Comment by futuresoup** [comment]
Thanks @andrew-polk for your quick response. Really excited you're working on this, it is sorely needed for our Docusaurus site and definitely our #1 priority to get this up and running.

**Comment by purplecarrot625** [comment]
> Thank you for the response, I have followed  the instructions and duplicated your notion-sample site. I don't think that I have changed any link or add new pages.
I am wondering where I can find the link like you mentioned " but left a link to 454a4e53ed0a46f6bd431b07328e8941 which is on our sample site but not yours."

**Comment by purplecarrot625** [comment]
Thanks @andrew-polk  for your response! I think I have figured out what happend! Appreciate your help!
