### ISSUE TITLE
How do I update the custom.css?

### ISSUE THREAD

**Issue by JenniBeadle** [sillsdev/docu-notion#59]
**Describe the bug**
After editing the custom.css directly on Github the release fails as the branch is out of date.
So how to I update the css from Notion?

**Reproduction Steps**
1. Edit the custom.css on GitHub and commit.
2. Edit the Notion file
3. Go to GitHub and run the release workflow
4. Release fails with the following message:
  `   Your branch and 'origin/main' have diverged,
     and have 61 and 1 different commits each, respectively.
     (use "git pull" to merge the remote branch into yours) `
See release  #102  
(https://github.com/sillsdev/paratext-manual/actions/runs/5724610706/job/15511446077) 

**Additional context**
I was trying to resolve several problems. So you will also see warnings about video links. I will write another issue about that.

**Comment by andrew-polk** [comment]
I think what happened is between the time that the Github Action checked out the branch and when it tried to commit its changes, another change was made to the same branch (main). Likely, that is when you made one of the custom.css changes.

If that's the case, I would expect you would only need to run the Action again so it can start with the latest changes in main.
Indeed, I see that the next time the Action ran it did succeed.

Closing for now, but feel free to continue if you think there is still an issue.
