### ISSUE TITLE
Release gives errors about crowdin dependencies

### ISSUE THREAD

**Issue by JenniBeadle** [sillsdev/docu-notion#66]
**Problem**
I tried to clear out some files tonight, but the release failed with two errors when trying to install crowdin dependencies.

## Error 1
Line 26
![image](https://github.com/sillsdev/docu-notion/assets/108683165/a8116b3f-cd30-4ee2-a117-477a417b0b5e)
After a lengthy exchange with Crowdin Chat support we finally found out that there was a problem with the **package.json**.
"crowdin": "crowdin", should be **"@crowdin/cli": "3.13.0",**

Then I got the next error.

## Error 2
Line 27
```
error Package "//pretranslate" refers to a non-existing file '"//pretranslate@  used to re-apply translations when files are renamed or reorganized"'.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Process completed with exit code 1.
``` 

Crowdin support confirms that it refers to a non-existing file. But not one of theirs. They recommended I check with you.

I notice the next two lines 28-29 look more like the commands on the page they sent me to. But they are commands not dependencies.
https://crowdin.github.io/crowdin-cli/commands/crowdin-pre-translate/

```
    "//pretranslate": "  used to re-apply translations when files are renamed or reorganized",
    "crowdin:pretranslate": "crowdin pre-translate --method tm --translate-untranslated-only --translate-with-perfect-match-only --verbose",
    "crowdin:sync": "docusaurus write-translations && crowdin upload sources --delete-obsolete && crowdin download"
```

Line 27 look more like a comment to me, so I tried deleting it. However, it resulted in the following error.
```
error An unexpected error occurred: "https://registry.yarnpkg.com/crowdin:pretranslate: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/home/runner/work/paratext-manual/paratext-manual/yarn-error.log".
```
Sorry, no sign on the yarn-error.log on GitHub.

I tried but that's as far as I can go. I hope it makes sense to you.

**Comment by andrew-polk** [comment]
Hi, @JenniBeadle.
As we discussed, this is not a docu-notion issue.
You and I are working through this via other channels.
