### ISSUE TITLE
Latex Rendering Problem

### ISSUE THREAD

**Issue by enfycius** [sillsdev/docu-notion#68]
# Problem

## Bug
Latex code is not properly rendered. For example, if you enter the following code "$$x$$", this code is only converted to "x".

# Solution

But, I solved this problem myself. First, you must modify the existing version of notion-to-md  package to the latest version "3.1.1". (23.08.13)

Second, the existing return statements of the doNotionToMarkdown function in the transforms.js file have to modified to ```return markdown.parent;```

**Comment by hatton** [comment]
@enfycius Do you want to make a PR? The main thing is to ensure that the notion-to-md doesn't break anything. It would be great if your PR could add a unit test for Latext rendering.

**Comment by enfycius** [comment]
> 

Sure. It's an honor for me to make a PR.

**Comment by enfycius** [comment]
@hatton Could you make a branch about this issue?
