### ISSUE TITLE
Add comment about CSS to readme

### ISSUE THREAD

**Issue by jellejurre** [sillsdev/docu-notion#85]
To convert a multi-column notion page to docusaurus markdown, the src/css/notion-styles.css css file is required to be included in the final markdown viewer. Without the flex box, the columns are placed under eachother

The readme does not mention this, so by following the readme, you get a project that doesn't have support for multi-column layouts

This can be fixed by adding a note to the readme that projects which don't copy the template site github project need to manually include the CSS file in their docusaurus (or other MD viewer) setup (for example by copying the contents of the src/css/notion-styles.css to the src/css/custom.css file for docusaurus)

**Comment by hatton** [comment]
Hi, could you improve on this bug report? Also, PR's are more than welcome.

**Comment by jellejurre** [comment]
Fair enough, PR should be clarified. Will make a pr soon

**Comment by hatton** [comment]
Thanks for the readme note. It occurs to me that people could end up with out-of-date copies of `notion-styles.css`. So we should find a way to write out the current version of `notion-styles.css` to the correct place with every call of docu-notion.

**Comment by hatton** [comment]
OK, 0.16 will automatically copy `docu-notion-styles.css` to the output directory.
