### ISSUE TITLE
[Question] How does it compares to notion-to-markdown

### ISSUE THREAD

**Issue by kmlbgn** [sillsdev/docu-notion#88]
Hey, may you allow me a potentially silly question:
After spending a little time on both codebases, I'm wondering what is the main difference between docu-notion and notion-to-markdown, as docu-notion extends from the latter.  They both achieve conversion to md and allow custom transformers to produce desired outputs format. 
I first thought that docu-notion was meant to produce outputs tailored for Docusaurus, but the readme suggests its actually generic.

Thanks a lot

**Comment by hatton** [comment]
Right, we only use docu-notion for Docusaurus sites, and are only interested in making sure it works well with Docusaurus. But the set of markdown files it produces would be useful for non-Docusaurus sites as well. Hope that helps.

**Comment by hatton** [comment]
Perhaps it was added later?

**Comment by kmlbgn** [comment]
Oh right, i'll try it out, thanks for answering @hatton

**Comment by kmlbgn** [comment]
@hatton my forked version now handles Category with index.md derived from its content. Can't PR cause had to change a few other things but the update is quite simple. Maybe you are interested.
