### ISSUE TITLE
Support links to sidebar sections

### ISSUE THREAD

**Issue by hatton** [sillsdev/docu-notion#9]
In Notion, you can of course link to one of the pages that serve as sections in the outline. But when docu-notion sees such a link, it doesn't find the page, and logs

> Could not find the target of this link. Note that links to outline sections are not supported. ded7393e-8194-4a68-ac04-81839baadac3

Docusaurus does now support links to sidebar sections that have [auto-generated table of contents](https://deploy-preview-5830--docusaurus-2.netlify.app/docs/next/sidebar/#generated-index-page) for the direct children. So if a project turned on that capability, it would make sense for docu-notion to be able to generate the link to get to it.

**Comment by andrew-polk** [comment]
You did figure out to make this work for https://docs.bloomlibrary.org/Release-Notes, but I'm not sure how to document what you did here.
Is it simply that you created an index page with a slug which matches the title of the group?

**Comment by hatton** [comment]
Right. To make this work in Docusaurus, you have to add an index page for the folder, and set the slug to the folder.

Example: when you click here:
![image](https://github.com/sillsdev/docu-notion/assets/8448/4fcc058a-f5ed-4acb-b89c-dc0e4dbc880c)

that takes you to https://docs.bloomlibrary.org/Release-Notes, and this works because there is this Notion document:

![image](https://github.com/sillsdev/docu-notion/assets/8448/4f62a7e3-abe8-4d11-90c8-c27ea63e8693)
