### ISSUE TITLE
"Mention Page" links don't point to local pages

### ISSUE THREAD

**Issue by hatton** [sillsdev/docu-notion#97]
Doing a "Link to Page" 
![image](https://github.com/sillsdev/docu-notion/assets/8448/53dfb87b-7f61-468d-8cb8-ddf709234fa1)
gives you a new block (not inline). The markdown that docu-notion gets is a nice relative path:
`[How to Embed a Bloom Library Collection In Your Website](/embed-collection)`
and Docu-notion handles that well.

However, doing "Mention Page"
![image](https://github.com/sillsdev/docu-notion/assets/8448/076fd535-65e7-4c6e-ba32-6f017d4884ce)
gives you a nice inline link:
![image](https://github.com/BloomBooks/bloom-docs/assets/8448/c5d4af4b-e515-471c-9bab-ddcfaa088971)
But the markdown that docu-notion gets is as a full URL:
`See also: [How to Embed a Bloom Library Collection In Your Website](https://www.notion.so/7bf1d2edfdfa421891a60e4c0af37d53) `
and docu-notion doesn't currently realize that this is part of this site. Instead, it leaves that full URL intact so that if you click on it, you go to notion.so instead of the page on your site.

**Comment by jamespostsil** [comment]
I just encountered this myself.

Should we just avoid using the "Mention page" or "Mention block" feature, or is this something that could/should be fixed?

**Comment by andrew-polk** [comment]
Fixed in v0.16.1
